default: &default
  adapter: postgresql
  encoding: utf8
  schema_search_path: "public"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exemple_rails_jwt_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: exemple_rails_jwt_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: postgres
  host: localhost